<?xml version="1.0" encoding="UTF-8"?>
<project>
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.cjx</groupId>
    <artifactId>business-platform</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>../../../pom.xml</relativePath>
  </parent>

  <artifactId>uibot-service</artifactId>
  <packaging>jar</packaging>

  <dependencies>
    <!-- 依赖自己的API模块 -->
    <dependency>
      <groupId>com.cjx</groupId>
      <artifactId>uibot-api</artifactId>
    </dependency>

    <dependency>
      <groupId>com.cjx</groupId>
      <artifactId>common-web</artifactId>
    </dependency>

    <dependency>
      <groupId>com.cjx</groupId>
      <artifactId>common-strategy</artifactId>
    </dependency>

    <dependency>
      <groupId>com.cjx</groupId>
      <artifactId>common-jpa</artifactId>
    </dependency>

    <dependency>
      <groupId>com.cjx</groupId>
      <artifactId>common-redis</artifactId>
    </dependency>

    <dependency>
      <groupId>com.cjx</groupId>
      <artifactId>common-dingtalk</artifactId>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <version>${spring-boot.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.11.0</version>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
          <compilerArgs>
            <arg>-parameters</arg>
          </compilerArgs>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>